- name: configure mysql
  hosts: mysql
  become: yes
  tasks:
  - name: configure mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes
