- name: configure mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install pip modules
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL

  - name: configure mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: ec2_user
      login_password: ExpenseApp@1
      login_host: db.harvargurram.online
    register: mysql_info
    ignore_errors: True
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
    when: mysql_info.failed is true

